### ISSUE TITLE
URL "blog.adesso.de" führt nicht zum Blog

### ISSUE THREAD

**Issue by s-gbz** [adessoAG/devblog#101]
Hallo zusammen,
seit einiger Zeit führt [blog.adesso.de](https://blog.adesso.de) lediglich zur normalen Website und nicht, wie erwartet, zum Blog. Der ist nur unter https://blog.adesso.de/de/news/blog/index.jsp erreichbar. Hinsichtlich der UX ist dies ein unerwartetes Verhalten. Ist das etwas, dass wir fixen können? 

Insofern hier kein Einfluss darauf genommen werden kann, könnte es lohnenswert sein die zuständige Partei (CCO?) diesbezgülich aufmerksam zu machen.

Viele Grüße
Sergej

**Comment by FrederikSchlemmer** [comment]
> Hallo zusammen,
> seit einiger Zeit führt [blog.adesso.de](https://blog.adesso.de/de) lediglich zur normalen Website und nicht, wie erwartet, zum Blog. Der ist nur unter https://blog.adesso.de/de/news/blog/index.jsp erreichbar. Hinsichtlich der UX ist dies ein unerwartetes Verhalten. Ist das etwas, dass wir fixen können?
> 
> Insofern hier kein Einfluss darauf genommen werden kann, könnte es lohnenswert sein die zuständige Partei (CCO?) diesbezgülich aufmerksam zu machen.
> 
> Viele Grüße
> Sergej

Der Blog ist bei mir weiterhin unter [blog.adesso.de](https://blog.adesso.de) erreichbar. Dein Link hat noch den Zusatz `/de` wodurch möglicherweise der Fehler kommt?

**Comment by s-gbz** [comment]
Der Zusatz scheint ein Kopierfehler gewesen zu sein. Beim händischen Tippen hatte ich lediglich blog.adesso.de gehabt.

Dennoch scheint der Fehler behoben zu sein 👍  (Temporär?q)
