### ISSUE TITLE
Lokale Jekyll-Vorschau: Seite auf "/" erreichbar machen

### ISSUE THREAD

**Issue by thombergs** [adessoAG/devblog#13]
Wenn ich lokal Jekyll zur Vorschau starte, ist die Seite unter `http://localhost:4000/devblog` erreichbar. Schöner wäre es, wenn die Seite unter `http://localhost:4000` erreichbar wäre, dann muss man nicht das suffix suchen.

Startpunkt: in der `_config.yml` die baseUrl setzen. Dann ist aber das CSS kaputt.

**Comment by thombergs** [comment]
Aktuell wir das Bild "trace.png" in meinem Blog Post nicht angezeigt, weil es auf "/assets" verweist und nicht auf "/devblog/assets". Also noch ein Grund, das "devblog" zu entfernen

**Comment by Calle-Lo** [comment]
Alles klar, aber generell würde die baseUrl keine Probleme machen. 
Damit das Bild auch angezeigt wird muss sich das Bild auch in dem angegeben Ordner befinden ich habe nämlich das Bild überhaupt nicht gefunden. Aber sonst hast du Recht dass das Bild dann unter "devblog/assets/..." erst zu finden ist.

Ich habe das jetzt aber schon mal bei mir gefixt und werde das pushen im Laufe des Tages.

**Comment by thombergs** [comment]
Hatte das Bild nicht committed. Habe ich jetzt nachgeholt

**Comment by Calle-Lo** [comment]
Lokale Ansicht jetzt über http://localhost:4000 erreichbar und das CSS ist wie gehabt. Hier habe ich die baseUrl leer gelassen da die normale URL schon http://localhost:4000 ist, deshalb war es wahrscheinlich bei dir kaputt. 
In der Preview 19# wird das Bild jetzt mit angezeigt
Dieser Issue wäre damit erledigt!
