### ISSUE TITLE
Lokale Jekyll-Vorschau: Header

### ISSUE THREAD

**Issue by thombergs** [adessoAG/devblog#15]
Aktuell werden Header ab h1 in der Detailseite genutzt. Nach der Besprechung mit dem CMS-Projekt dürfen die Überschriften innerhalb eines aber erst mit h3 anfangen.

Ist:
\# = h1
\## = h2
\### = h3

Soll:
\# = h3
\## = h4
\### = h5

**Comment by Calle-Lo** [comment]
Habe ich erledigt, aber sollten die Header nicht ab h4 bis h6 unterstützt werden, weil das steht bei mir auf dem Zettel?

**Comment by thombergs** [comment]
Ja, bitte so umsetzen wie du das aufgeschrieben hast, dann habe ich mich vertan.

Bitte auch sie Erläuterung im Beispielpost dann anpassen, da hatte ich einen Abschnitt dazu ergänzt.

**Comment by Calle-Lo** [comment]
Ich habe die Erläuterung im Beispielpost angepasst und die Header auf h4 bis h6 gestellt. Das heißt bei einem jekyll build werden nur die Header h4 bis h6 erzeugt, wenn der Autor die von dir beschriebenen Markdown Header angaben verwendet. Alles darüber hinaus resultiert in einem h6.
