### ISSUE TITLE
Buchstabe im Namen fehlt

### ISSUE THREAD

**Issue by pschild** [adessoAG/devblog#156]
Hi,

in einem [bereits veröffentlichten Post](https://www.adesso.de/de/news/blog/kollegin-alexa-wie-sprachassistenten-ein-it-projektteam-unterstuetzen-koennen.jsp) von mir fehlt ein "c" in meinem Nachnamen, sowohl im Teaser, als auch im Post selbst.
Ist: Philippe Shild
Soll: Philippe Schild

Die `authors.yml` sieht m.E. korrekt aus.
Könnt ihr euch das mal anschauen?

**Comment by jo2** [comment]
Der Fehler scheint nicht bei uns zu liegen, in den [exportierten Daten](https://github.com/adessoAG/devblog/blob/master/assets/first-spirit-xml/2020-04-20/2020-04-20-wie-alexa-ein-it-projektteam-unterstuetzen-kann.xml) und in der [Preview](https://5e9d7cdf9cfa280007aad6ef--adesso-devblog-pr-preview.netlify.app/) ist es jeweils korrekt. Ich leite das mal weiter.

**Comment by DiDoHH** [comment]
Hallo, 
der Fehler ist behoben. Könnt Ihr das Issue bitte schließen?
Viele Grüße
Diana

**Comment by pschild** [comment]
Ich hab's gerade geprüft - Fehler ist behoben. Danke!
