### ISSUE TITLE
Idee: Ein Previewbild pro Blogpost

### ISSUE THREAD

**Issue by s-gbz** [adessoAG/devblog#157]
Mir ist aufgefallen, dass die Darstellung der kürzlich veröffentlichten Artikel monoton aussieht:
![image](https://user-images.githubusercontent.com/23424538/82141632-72828100-9837-11ea-8223-d76f1dbbc1f9.png)

Wenn wir anfangen für neue Blogposts ein Bild zu hinterlegen, können wir die Ansehnlichkeit steigern und Besucher umso mehr motivieren auf unsere Artikel zu clicken.

**Comment by acetous** [comment]
Das Design der Webseite liegt bei CCO und nicht bei uns. Ich nehme das mal mit.
