### ISSUE TITLE
Lokale Jekyll-Vorschau: XML-Posts aus Übersichtsseite entfernen

### ISSUE THREAD

**Issue by thombergs** [adessoAG/devblog#16]
Die Blog Posts werden in der Übersichtsseite sowohl in der XML- als auch in der HTML-Version verlinkt. In der Vorschau sollte nur die HTML-Version angezeigt werden, damit man die Blog Posts vernünftig reviewen kann.

**Comment by Calle-Lo** [comment]
Ja, dieses Problem wird halt vom jekyll2cms, schon gelöst, da die XML-Version ebenfalls in den Ordner mit rein gepackt werden, diese werden nach dem jekyll build von dem jekyll2cms dann gelöscht.
Jekyll holt sich dann automatisch alles was in dem Ordner ist und zeigt das dann an, darum macht das jekyll2cms die Arbeit was halt lokal nicht gegeben ist.

**Comment by Calle-Lo** [comment]
Da in den Markdown Dateien zwei Layouts angegeben werden, werden beide Layouts in der Übersichtsseite angezeigt. 
Lösung: Sage beim generieren der Übersichtsseite, dass du nur die Posts haben möchtest, die das HTML-Layout nutzen. Die Folge daraus ist es werden für das Pagination pro Seite auch nur die Hälfte der gewünschten Zeitenanzahl angezeigt. --> verdoppeln der Beiträge pro Seite.

**Comment by thombergs** [comment]
In der Preview wird der XML-Beitrag aber immer noch angezeigt: https://adesso-devblog-preview.netlify.com/

**Comment by Calle-Lo** [comment]
Ja weil ich die Änderungen noch auf das Repo pushen muss aber nebenbei halt auch noch an einer anderen Änderung arbeite, die noch nicht ganz fertig ist. 
Ich wollte jetzt nichts unfertiges auf das Repo pushen.
