### ISSUE TITLE
Neue Kategorien ab dem 01.07.2021

### ISSUE THREAD

**Issue by DiDoHH** [adessoAG/devblog#204]
Hallo zusammen,

ab dem 01.07.2021 werden wir (CCO) die Kategorien für den Blog ändern.

Für euch relevant/interessant: Es werden zwei neue Kategorien veröffentlicht. Zum einen **KI** und zum anderen **Digital Experience**

Könnt Ihr diese bitte in eure Dokumentation mit aufnehmen? Geplant ist auch bis zum Ende des Jahres die Kategorie **Cloud**. Wenn sich da ein paar Postings finden, können wir uns auch vorstellen die Kategorie früher zu veröffentlichen.

Bei Fragen kommt gerne auf uns zu.

Viele Grüße
Diana

**Comment by DiDoHH** [comment]
Wie gehen wir hier mit dem CSS für eure Vorschau im netlify um? Soll ich euch die Hex-Codes der Kategorien nennen oder wollt ihr ein Update vom CSS machen? Letzteres würde aber für euch bedeuten, das ihr auch die Klassennamen im HTML anpassen müsst. Wir sind davon weggegangen die CSS-Klassen so zu benennen, wie die Kategorie lautet, da es da in der Vergangenheit schon zu Änderungen kam und wir diese in diesem Zug auch wieder anpassen müssten.

**Comment by jo2** [comment]
Hallo Diana,

wenn du uns die HEX-Codes schicken, bzw hier posten könntest, wäre das gut, dann baue ich das ein.

Viele Grüße
Johannes

**Comment by DiDoHH** [comment]
Hallo Johannes,

sorry.. So ne Woche ist echt zu kurz... Die Farben sind jetzt mit der Redaktion abgestimmt.

KI bekommt #995219 (ehem. Microsoft)
Digital Experience #a79300 (ehem. Java)
Cloud bekommt  #5e5300

Cloud wird für Herbst angepeilt. Wie gesagt, wenn Ihr Blog-Posts habt, die dort hinein passen würden, kann mit der Redaktion abgestimmt werden, ob die Kategorie früher kommt. Gerne kann ich dann nochmal ein Issue erstellen, dass eure Doku entsprechend erweitert wird.

Viele Grüße

Diana

**Comment by jo2** [comment]
Welche Farben sind denn dann für Java und Microsoft vorgesehen, wenn die bisherigen Farben jetzt anderweitig verwendet werden?
