### ISSUE TITLE
Umstellung der Autoren-Infos

### ISSUE THREAD

**Issue by DiDoHH** [adessoAG/devblog#205]
Hallo zusammen,

in der Vergangenheit kam es auch hier immer mal wieder vor, das mehrere Autoren an einem Blog-Post zusammen geschrieben haben. Das führt dazu, das im CMS ein neuer Autor angelegt werden muss. Davon wollen wir künftig absehen.

Aktuell gebt Ihr im XML folgende Autoren-Daten beispielsweise an das CMS mit

 ```
<!--Author Information-->
<field name="author_first_name"><![CDATA[Cem]]></field>
<field name="author_last_name"><![CDATA[Caylak]]></field>
<field name="author_id"><![CDATA[ccaylak]]></field>
<field name="author_picture_stored_only"><![CDATA[http://localhost:4000/assets/images/avatars/ccaylak.png]]></field>
```
Die Informationen author_first_name, author_last_name und author_picture_stored_only werden beim Import nicht berücksichtigt und somit auch von unserer Seite nicht benötigt. Wenn Ihr wollt und Ihr die Informationen an dieser Stelle nicht wo anders benötigt, können die Daten aus dem XML enfallen.

Zusätzlich würden wir allerdings dann eine "Liste" von author_id erwarten. Wobei diese Liste insofern keine Liste darstellt. Wir können uns vorstellen, dass die Authoren dann, analog zu Tags, untereinander genannt werden. z.B.
```
<!--Author Information-->
<field name="author_id"><![CDATA[ccaylak]]></field>
<field name="author_id"><![CDATA[dsorna]]></field>
<field name="author_id"><![CDATA[florianluediger]]></field>
```
Könnt Ihr dies so bereitstellen?

Bei Fragen kommt gerne auf mich zu.

Viele Grüße
Diana

**Comment by jo2** [comment]
Hallo Diana,

wie stellt ihr denn dann die Verbindung zwischen author_id und der realen Person her? Oder liegen die Daten auch noch irgendwo extern, sodass ihr darüber zugreifen könnt?

Viele Grüße
Johannes

**Comment by DiDoHH** [comment]
Hallo Johannes,

die Autoren müssen vorher (bisher auch schon) in unserer Autorendatenbank liegen. Dort sind auch die Autoren-IDs gepflegt.
Wir können da gerne mal zusammen reinschauen, wenn du möchtest.

Viele Grüße
Diana

**Comment by DiDoHH** [comment]
Hallo @jo2 @acetous, 

gibt es  hier schon einen Status? Bis wann könnt Ihr die Anpassung vorsehen/durchführen? Wir müssen das entsprechend mit unserem Release-Plan abstimmen.

Viele Grüße
Diana
