### ISSUE TITLE
Adopt the new blog design

### ISSUE THREAD

**Issue by florianluediger** [adessoAG/devblog#51]
The [main adesso blog](http://blog.adesso.de) has got a design overhaul, which should be adopted in this preview.

**Comment by silasmahler** [comment]
Yes, we will need to wait for the new files from arithnea.

**Comment by silasmahler** [comment]
Die Dateien sind da und liegen im Confluence auf der Seite devblog.
Wer sich dafür berufen fühlt, kann ja mal versuchen das Layout einzubinden.
@adessoAG/devblog

**Comment by FrederikSchlemmer** [comment]
Fixed #91
