### ISSUE TITLE
Teaser text not displayed in detail page

### ISSUE THREAD

**Issue by thombergs** [adessoAG/devblog#54]
In a published blog post the teaser text is not displayed on the detail page of a blog post. 

TODO: Add the teaser text to the xml output

**Comment by silasmahler** [comment]
Das ist merkwürdig. Der Teasertext befindet sich neben dem normalen Text ein weiteres Mal im separaten Bereich "Teaser" etwas darüber in der XML. Ich würde das Problem deshalb beim Importer vermuten, vllt hat ea dort ja Änderungen gegeben.

**Comment by florianluediger** [comment]
[This blog post](https://github.com/adessoAG/devblog/blob/master/assets/first-spirit-xml/2018-06-15/2018-06-15-microservice-kommunikationsmuster.xml) is a good example to explain the problem.

As you can see, the teaser text is contained in the `teaser` and `display_content` XML fields. However the adesso blog only includes the contents of the `content` field in the detail page of a blog post.

Also adding the teaser text to the `content` field should fix the problem.
