### ISSUE TITLE
Preview lädt sehr lange

### ISSUE THREAD

**Issue by thombergs** [adessoAG/devblog#85]
Die Previews der PRs dauern aktuell sehr lange zu laden. Im Footer des Browser steht dabei immer, dass er versucht auf "www.adesso.de" zuzugreifen. Das muss gefixt werden, sonst ist die Arbeit mit den Previews nicht wirklich möglich.

**Comment by florianluediger** [comment]
Ich kann das bei mir nicht reproduzieren, was genau meinst du damit, dass die Previews lange zu laden dauern? Wenn ich im PR die Preview öffne, kommt ziemlich schnell die Seite mit allen aktuellen Blogposts und wenn ich einen bestimmten Post auswähle, wird dieser mir auch in kürzester Zeit angezeigt.
