### ISSUE TITLE
Geschweifte Klammern in Codeschnipseln escapen

### ISSUE THREAD

**Issue by florianluediger** [adessoAG/devblog#95]
In #92 ist aufgefallen, dass doppelte, geschweifte Klammern in Codeschnipseln von Jekyll als Liquid-Tag erkannt werden und diese somit im fertigen Artikel fehlen.

Eine Lösung dafür ist [hier auf Stackoverflow](https://stackoverflow.com/questions/3426182/how-to-escape-liquid-template-tags/5866429#5866429) beschrieben. Wir sollten diese Information entweder irgendwo erwähnen, oder das dort erwähnte Plugin einbinden.

**Comment by s-gbz** [comment]
Ist das Problem noch aktuell? Ich könnte dies unter https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting erwähnen.

**Comment by florianluediger** [comment]
Ich kann nicht nachvollziehen, ob das Problem noch aktuell ist. Ich habe nicht mitbekommen, dass das irgendwann mal gefixt worden wäre, also nehme ich an, dass das Problem noch besteht.
