### ISSUE TITLE
Codeschnipsel werden im adesso Blog nicht richtig dargestellt

### ISSUE THREAD

**Issue by florianluediger** [adessoAG/devblog#96]
In unserer Preview ist noch alles korrekt, in dem tatsächlichen adesso Blog werden bei Codeschnipseln allerdings alle Leerzeilen gelöscht und die erste Zeile ein kleines Stückchen eingerückt.

Ein Beispiel findet sich in diesem Artikel:
- [Preview](https://deploy-preview-94--adesso-devblog-preview.netlify.com/blog-posts/2019-02-18/micronaut/micronaut)
- [adesso Blog](https://www.adesso.de/de/news/blog/micronaut-eine-alternative-zu-spring-4.jsp)

Dieses Issue soll nur der Dokumentation dienen, ich werde per E-Mail Kontakt zur Arithnea aufnehmen.

**Comment by florianluediger** [comment]
Habe heute nochmal nachgehakt, es scheint an der Art wie Blogposts aus FirstSpirit heraus gerendert werden zu liegen. Milan wird sich das ganze nochmal anschauen.

Aktuelles Beispiel dazu:
- Artikel im adesso-Blog: https://www.adesso.de/de/news/blog/micronaut-eine-alternative-zu-spring-4.jsp
- Markdown-Datei: https://github.com/adessoAG/devblog/pull/83/files#diff-4bb7b6fd49f36407ea2d947c7c6f0f72R71-R94
- Auch in der XML-Datei wird der Code korrekt formatiert: https://github.com/adessoAG/devblog/blob/master/assets/first-spirit-xml/2019-02-18/2019-02-18-Micronaut.xml#L105-L127

**Comment by s-gbz** [comment]
Kann ich aktuell nicht reproduzieren. Scheint sich erstmal geklärt zu haben.
